# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  packages: write
  pages: write
  repository-projects: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -c ./...

    - name: Go coverage report
      uses: ncruces/go-coverage-report@v0.3.0    
      with:
        chart: true
        amend: true
            
